const sectors = [
    {
        name: 'Développement Digital',
        desc: 'Le tronc commun en Développement Digital est une étape importante pour acquérir les bases nécessaires à l\'étude, la conception, la construction',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/developpement-digital/',
        models: [
            "Arabe",
            "Français",
            "Anglais technique/Espagnole",
            "Culture entrepreneuriale-Partie 1",
            "Compétences comportementales et sociales",
            "Entrepreneuriat-PIE 1",,
            "Culture et techniques avancées du numérique",
            "Se situer au regard du métier et de la démarche de formation",
            "Acquérir les bases de l’algorithmique",
            "Programmer en Orienté Objet",
            "Développer des sites web statiques",
            "Programmer en JavaScript",
            "Manipuler des bases de données",
            "Développer des sites web dynamiques",
            "S’initier à la sécurité des systèmes d’information"
            ]
    },
      {
        name: 'Développement Digital Option Full Stack',
        desc: 'Le développeur full stack est un développeur touche-à-tout et complet, qui travaille à la fois côté Backend et Frontend.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/developpement-digital-option-web-full-stack/',
        models: [
            "Français",
            "Anglais technique",
            "Culture entrepreneuriale",
            "Compétences comportementales",
            "Entrepreneuriat-PIE 2",
            "Culture et techniques avancées du numérique",
            "Préparation d’un projet web",
            "Approche agile",
            "Gestion des données",
            "Développement front-end",
            "Développement back-end",
            "Création d’une application Cloud native",
            "Projet de synthèse",
            "Intégration du milieu professionnel"
            ]
    },
      {
        name: 'Développement Digital Option Mobile',
        desc: 'Le développement mobile se définit par à la création et la diffusion d’applications portables, destinées aux entreprises ou aux particuliers, dans le respect d’une charte de fiabilité et de sécurité stricte.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/developpement-digital-option-applications-mobiles/',
        models: [
            "Français",
            "Anglais technique",
            "Culture entrepreneuriale",
            "Compétences comportementales",
            "Entrepreneuriat-PIE 2",
            "Culture et techniques avancées du numérique",
            "Bases du développement Android",
            "Programmation KOTLIN",
            "Gestion de projet ",
            "Initiation aux composants et modèle d’une application Android ",
            "Développement des interfaces utilisateurs sous Android ",
            "Elaboration d’une application Android sécurisée ",
            "Développement des applications IOS ",
            "Développement multiplateforme ",
            "Intégration du milieu professionnel"
            ]
    },
]
