const sectors = [
    {
        name: 'Développement Digital',
        desc: 'Le tronc commun en Développement Digital est une étape importante pour acquérir les bases nécessaires à l\'étude, la conception, la construction',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/developpement-digital/',
        models: [
            "Arabe",
            "Français",
            "Anglais technique/Espagnole",
            "Culture entrepreneuriale-Partie 1",
            "Compétences comportementales et sociales",
            "Entrepreneuriat-PIE 1",
            "Culture et techniques avancées du numérique",
            "Se situer au regard du métier et de la démarche de formation",
            "Acquérir les bases de l’algorithmique",
            "Programmer en Orienté Objet",
            "Développer des sites web statiques",
            "Programmer en JavaScript",
            "Manipuler des bases de données",
            "Développer des sites web dynamiques",
            "S’initier à la sécurité des systèmes d’information"
            ]
    },
      {
        name: 'Développement Digital Option Full Stack',
        desc: 'Le développeur full stack est un développeur touche-à-tout et complet, qui travaille à la fois côté Backend et Frontend.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: false,
        link: 'https://ofppt.info/developpement-digital-option-web-full-stack/',
        models: [
            "Français",
            "Anglais technique",
            "Culture entrepreneuriale",
            "Compétences comportementales",
            "Entrepreneuriat-PIE 2",
            "Culture et techniques avancées du numérique",
            "Préparation d’un projet web",
            "Approche agile",
            "Gestion des données",
            "Développement front-end",
            "Développement back-end",
            "Création d’une application Cloud native",
            "Projet de synthèse",
            "Intégration du milieu professionnel"
            ]
    },
      {
        name: 'Développement Digital Option Mobile',
        desc: 'Le développement mobile se définit par à la création et la diffusion d’applications portables, destinées aux entreprises ou aux particuliers, dans le respect d’une charte de fiabilité et de sécurité stricte.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: false,
        link: 'https://ofppt.info/developpement-digital-option-applications-mobiles/',
        models: [
            "Français",
            "Anglais technique",
            "Culture entrepreneuriale",
            "Compétences comportementales",
            "Entrepreneuriat-PIE 2",
            "Culture et techniques avancées du numérique",
            "Bases du développement Android",
            "Programmation KOTLIN",
            "Gestion de projet ",
            "Initiation aux composants et modèle d’une application Android ",
            "Développement des interfaces utilisateurs sous Android ",
            "Elaboration d’une application Android sécurisée ",
            "Développement des applications IOS ",
            "Développement multiplateforme ",
            "Intégration du milieu professionnel"
            ]
    },
    {
        name: 'Gestion Des Entreprises',
        desc: 'La formation technicien spécialisé en gestion des entreprises est une formation généraliste qui couvre tous les aspects de l’entreprise : Marketing, Finance, Économie, Gestion des ressources humaines, comptabilité, communication, etc.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/accueil/technicien-specialise/tsge-technicien-specialise-en-gestion-des-entreprises/',
        models: [
            "Arabe",
            "Communication Ecrite et Orale",
            "Anglais technique",
            "Législation/PME",
            "Métier et Formation dans le secteur AGC",
            "Bureautique",
            "L’entreprise et son environnement",
            "Statistiques",
            "Comptabilité générale : les concepts de base",
            "Marketing",
            "Comptabilité générale : les opérations courantes",
            "Traitement des salaires",
            "Comptabilité générale : les écritures d’inventaire et de régularisation",
            "Logiciel de gestion commerciale, comptable et de paie",
            "Fiscalité de l’entreprise",
            "Mathématiques financières",
            "Diagnostic financier",
            "Gestion de production et des approvisionnements",
            "Contrôle de gestion 1 : Comptabilité Analytique d’Exploitation",
            "Gestion des ressources humaines",
            "Marketing stratégique",
            "Contrôle de gestion 2: Gestion Budgétaire et Tableau de Bord",
            "Dossier de création d’entreprise",
            "Stage en entreprise"
            ]
    },
     {
        name: 'Secrétariat de Direction',
        desc: 'La secrétaire de direction joue le rôle de secrétariat de direction au sein de l’entreprise. Elle réalise les tâches administratives et l’accueil des visiteurs. Elle organise le travail de son service et s’occupe également de la gestion de l’agenda du directeur, parfois de tout le département administratif. La rédaction des comptes rendus, des rapports et des lettres fait également partie de son quotidien.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/tsd-technique-de-secretariat-de-direction/',
        models: [
            "Arabe",
            " Communication écrite et orale (Notions de français)",
            "Anglais technique",
            "Législation/PME",
            "Métier et Formation",
            "L’entreprise et Son environnement",
            "Etude du clavier et initiation à la bureautique",
            "Nouvelles technologies de l’information et de communication",
            "Correspondance d’affaires en arabe",
            "Documents et calculs commerciaux",
            "Communication interpersonnelle",
            "Correspondance d’affaires en français",
            "Techniques de gestion du fonds documentaire",
            "Techniques de gestion du temps",
            "Techniques de prise de notes",
            "Bureautique en arabe",
            "Communication en anglais",
            "Bureautique avancée",
            "Technique de recherche d’emploi",
            "Correspondance d’affaires en anglais",
            "Notion en comptabilité",
            "Logiciel de gestion commerciale",
            "Production des documents ( les écrits professionnels )",
            "SGBDR",
            "Préparations d’activités",
            "Outils de résolutions de problèmes",
            "Etude de cas dans l’entreprise Fil d’Art",
            "Dossier de création d’entreprise",
            "Stage en entreprise"
            ]
    },
     {
        name: 'Commerce',
        desc: 'Le concept de cette filière désigne la succession d’activités menées par des acteurs pour produire, transformer, vendre et consommer un produit. Ce produit peut être agricole, artisanal, industriel, touristique, informatique, etc.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/accueil/technicien-specialise/tsc-technicien-specialise-en-commerce/',
        models: [
            "Arabe",
            " Communication écrite et orale",
            "Anglais technique",
            "Législation/PME",
            "Métier et Formation dans le secteur AGC",
            "Bureautique",
            "L’entreprise et Son environnement",
            "Statistique",
            "Marketing fondamental",
            "Univers de la distribution au Maroc",
            "Calculs commerciaux",
            "Comptabilité générale : Concepts de base",
            "Approvisionnements",
            "Merchandising",
            "Techniques de vente et de négociation",
            "Documents commerciaux et gestion de la caisse",
            "Techniques de recherche d’emploi",
            "Introduction au Droit Commercial",
            "Logiciel de gestion commerciale SAARI",
            "Environnement international",
            "Marketing international",
            "Management de la force de vente",
            "Management de la relation client",
            "Anglais commercial",
            "Commerce électronique",
            "Techniques juridiques à l’international",
            "Techniques logistiques du commerce international",
            "Paiement et financement à l’international",
            "Dossier de création d’entreprise",
            "Stage en entreprise"
            ]
    },
]
