const sectors = [
    {
        name: 'Développement Digital',
        desc: 'Le tronc commun en Développement Digital est une étape importante pour acquérir les bases nécessaires à l\'étude, la conception, la construction',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/developpement-digital/',
        models: [
            "Arabe",
            "Français",
            "Anglais technique/Espagnole",
            "Culture entrepreneuriale-Partie 1",
            "Compétences comportementales et sociales",
            "Entrepreneuriat-PIE 1",
            "Culture et techniques avancées du numérique",
            "Se situer au regard du métier et de la démarche de formation",
            "Acquérir les bases de l’algorithmique",
            "Programmer en Orienté Objet",
            "Développer des sites web statiques",
            "Programmer en JavaScript",
            "Manipuler des bases de données",
            "Développer des sites web dynamiques",
            "S’initier à la sécurité des systèmes d’information"
            ]
    },
      {
        name: 'Développement Digital Option Full Stack',
        desc: 'Le développeur full stack est un développeur touche-à-tout et complet, qui travaille à la fois côté Backend et Frontend.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: false,
        link: 'https://ofppt.info/developpement-digital-option-web-full-stack/',
        models: [
            "Français",
            "Anglais technique",
            "Culture entrepreneuriale",
            "Compétences comportementales",
            "Entrepreneuriat-PIE 2",
            "Culture et techniques avancées du numérique",
            "Préparation d’un projet web",
            "Approche agile",
            "Gestion des données",
            "Développement front-end",
            "Développement back-end",
            "Création d’une application Cloud native",
            "Projet de synthèse",
            "Intégration du milieu professionnel"
            ]
    },
      {
        name: 'Infrastructure digital',
        desc: 'La filière infrastructure digital se réfère à l'ensemble des éléments technologiques essentiels au fonctionnement des services numériques, comprenant notamment les réseaux, les serveurs et les logiciels.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/infrastructure-digitale/',
        models: [
            "Français",
            "Arabe",
            "Anglais technique/Espagnole",
            "Culture entrepreneuriale-Partie 1",
            "Compétences comportementales et sociales",
            "Entrepreneuriat-PIE 1",
            "Culture et techniques avancées du numérique",
            "Se situer au regard du métier et de la démarche de formation",
            "Comprendre les enjeux d’un système d’information",
            "Concevoir un réseau informatique",
            "Fonctionnement du système d’exploitation",
            "Gérer une infrastructure virtualisée",
            "Automatiser les tâches d’administration",
            "Sécuriser un système d’information",
            "Développer une veille technologique"
            ]
    },
    {
        name: 'Gestion Des Entreprises',
        desc: 'La formation technicien spécialisé en gestion des entreprises est une formation généraliste qui couvre tous les aspects de l’entreprise : Marketing, Finance, Économie, Gestion des ressources humaines, comptabilité, communication, etc.',
        type: 'Technicien Spécialisé',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/accueil/technicien-specialise/tsge-technicien-specialise-en-gestion-des-entreprises/',
        models: [
            "Arabe",
            "Communication Ecrite et Orale",
            "Anglais technique",
            "Législation/PME",
            "Métier et Formation dans le secteur AGC",
            "Bureautique",
            "L’entreprise et son environnement",
            "Statistiques",
            "Comptabilité générale : les concepts de base",
            "Marketing",
            "Comptabilité générale : les opérations courantes",
            "Traitement des salaires",
            "Comptabilité générale : les écritures d’inventaire et de régularisation",
            "Logiciel de gestion commerciale, comptable et de paie",
            "Fiscalité de l’entreprise",
            "Mathématiques financières",
            "Diagnostic financier",
            "Gestion de production et des approvisionnements",
            "Contrôle de gestion 1 : Comptabilité Analytique d’Exploitation",
            "Gestion des ressources humaines",
            "Marketing stratégique",
            "Contrôle de gestion 2: Gestion Budgétaire et Tableau de Bord",
            "Dossier de création d’entreprise",
            "Stage en entreprise"
            ]
    },
     {
        name: 'Assistant Administratif',
        desc: 'L'Assistante Administrative s'occupe principalement de maintenir une bonne gestion administrative de la structure où elle exerce, en effet, elle se charge du suivi de dossiers (frappe de courrier, mise en forme de document...) et fait suivre les informations (e-mail, notes, fax...) pour le compte d'un responsable ou d'un ou plusieurs services en fonction de l'organisation de l'entreprise. Elle s'occupe parfois du traitement administratif complet de dossiers (contrats de maintenance des équipements, de la structure...).',
        type: 'Technicien',
        system: 'Cours du jour',
        get: 'Diplomante',
        tronc: true,
        link: 'https://ofppt.info/technicien-assistant-administratif/',
        models: [
            "Arabe",
            "Français",
            "Anglais technique",
            "Culture entrepreneuriale",
            "Compétences comportementales",
            "Entrepreneuriat-PIE 1",
            "Culture et techniques avancées du numérique",
            "Métiers et formation dans le secteur GC",
            "Introduction au droit",
            "Entreprise et son environnement",
            "Comptabilité Générale : concepts de base et opérations courantes",
            "Techniques d’accueil",
            "Gestion documentaire",
            "Techniques Quantitative de Gestion",
            "Marketing fondamental",
            "Ecrits professionnels",
            "Logiciel comptable et commercial",
            ]
    },
]
